### ISSUE TITLE
Manuális kód átvizsgálás + Statikus analízis

### ISSUE THREAD

**Issue by tuku13** [BME-MIT-IET/iet-hf-2022-twitch-tv-miszterek_#2]
- [x] Code review
- [x] SonarLint által jelzett hibák átvizsgálása, kijavítása
- [x] SonarCloud által jelzett hibák átvizsgálása, kijavítása

**Comment by peczedavid** [comment]
A SonarCloud csak az AndroidManifest.xml-ben jelez hibát, azt javítani nem tudjuk, azon kívül minden rendben. SonarLint sem jelez semmit.

**Comment by tuku13** [comment]
Befejeztük (@peczedavid  @tuku13 ) a Code Review-t. Egyet értünk a hozott változásokban, más átírható dolgot nem találtunk, főleg a statikus analízis után. A kód olvashatóbb, jobban szervezett lett.

**Comment by nagyerik99** [comment]
Sikeres merge, az issue feloldva.
